Development
finos/a11y-theme-builder pull request #885
Opened 2024-05-15 08:43 UTC by ravjot07

Contributes to #865

2024-05-15 08:46 UTC, ravjot07 commented
@aaronreed708 sir pl review this PR

2024-05-15 15:21 UTC, aaronreed708 requested changes
I loved your content, very well written!  Please make the changes indicated and then we can wrap this up.  Thanks!

2024-05-15 15:21 UTC, aaronreed708 commented on docs/designers/how-to-work-with-tokens.md
> +
capitalization again

2024-05-15 15:21 UTC, aaronreed708 commented on docs/designers/Understanding-Design-Concepts-Used.md
> +
Please use capitalization consistent with the rest of the documentation.  So here, please use "A11y Theme Builder".

I think that you need to tie Atomic Design and design tokens together since they are not necessarily related.  Also, design tokens are not generated in CSS, so you can probably drop that.  Maybe, "Built on Brad Frost's Atomic Design, A11y Theme Builder generates each design system in JSON, containing design tokens categorized in the appropriate atomic design elements.  Theme Builder also generates each design system in CSS."

2024-05-15 15:21 UTC, aaronreed708 commented on docs/designers/Understanding-Design-Concepts-Used.md
> +
I think you can drop the first sentence since you already mention Atomic Design and Brad Frost in the just above here.  Just say, "Atomic Design offers a structured approach..." and go on from there.

2024-05-15 15:21 UTC, aaronreed708 commented on docs/designers/Understanding-Design-Concepts-Used.md
> +
"Here's a breakdown of atom categories provided" doesn't sound right.  I wouldn't call them atom categories.  Maybe "Here is a list of some of the atoms used in Theme Builder" or "Here's a breakdown of the atoms defined by Theme Builder".  Something like that.

2024-05-15 19:37 UTC, ravjot07 commented
> I loved your content, very well written! Please make the changes indicated and then we can wrap this up. Thanks!

Thanks sir i am done with the changes. pl check

2024-05-15 19:37 UTC, ravjot07 commented on docs/designers/Understanding-Design-Concepts-Used.md
> +
done sir

2024-05-15 19:37 UTC, ravjot07 commented on docs/designers/Understanding-Design-Concepts-Used.md
> +
done sir

2024-05-15 19:37 UTC, ravjot07 commented on docs/designers/Understanding-Design-Concepts-Used.md
> +
done sir

2024-05-15 19:38 UTC, ravjot07 commented on docs/designers/how-to-work-with-tokens.md
> +
done sir and checked everywhere

2024-05-18 05:11 UTC, aaronreed708 approved these changes
Look great!  Thank you for your contribution!

2024-05-18 05:12 UTC, merged

2024-05-18 10:33 UTC, ravjot07 commented
> Look great! Thank you for your contribution!

Thanks sir